# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestQueue' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

  source 'http://gitlab.provectus-it.com/reinvently/cocoapod-specs.git'
  # Pods for TestQueue
  pod 'MessageQueue'
end
